GroupBy Merge Or Join

In [1]:
import pandas as pd

GroupBy

In [5]:
exp=pd.read_excel("subdata_pandas/expense-2.xlsx")
exp.head(5)

        Date    Category Sub-Category   Amount Payment Mode
0 2023-01-01     Grocery       Grocery      30         Cash
1 2023-01-02        Food    Restaurant     890          UPI
2 2023-01-04        Food        Zomato     257         Cash
3 2023-01-06  Essentials         Diary     120          UPI
4 2023-01-06  Essentials       Perfume    1500         Cash

In [ ]:
# find the total expense for each ccategory
exp.groupby("Category")['Amount'].sum()
exp.groupby("Category")['Amount'].agg(['sum'])

# Give a complete expense summary for each category
exp.groupby("Category")['Amount'].agg(['sum','count','mean','max','min'])

#How much money was paid by each payment mode
exp.groupby("Payment Mode")['Amount'].agg(['sum'])
'''	        
Payment Mode	sum
Card	       17780
Cash	       4944
UPI	           7425
'''

#How many transaction were made by each payment mode 
exp.groupby("Payment Mode")['Amount'].agg(['sum','count'])

#For each payment mode calculate the total amount spent on each category
exp.groupby(["Payment Mode","Category"])['Amount'].agg(['sum',"count"])

#Which category has the highest total expense
exp.groupby('Category')['Amount'].sum().sort_values(ascending=False)

# highest amount spent on each category 
e=exp.groupby(["Category"])['Amount'].agg(['max']) # to print highest amount spent on each category in descending order
e.max()         #to print highest max amount spent among all the categories

Category
Bills         18724
Essentials     4485
Food           3022
Clothes        2890
Grocery        1028
Name: Amount, dtype: int64

In [ ]:
#---------------Task-----------------------
# Create a DataFrame containing the total expense of each category.
# What is the average transaction amount for each payment mode?
# Find the highest individual transaction in each category
# Show total, average, minimum and maximum transaction amount for each payment mode.

MergeOrJoin

In [27]:
cust=pd.read_csv("subdata_pandas/customer.csv")
cust
payment=pd.read_csv("subdata_pandas/payment.csv")
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

In [ ]:
#Inner join : matching column from left and right
pd.merge(left=cust,right=payment,on='customerid',how='inner') 

#Left join : all values from left table matching values from rigtht table
pd.merge(left=cust,right=payment,on='customerid',how='left')

#right join : all values from right table matching values from left table
pd.merge(left=cust,right=payment,on='customerid',how='right')


#----task------
#cross join : all values from left table matching values from rigth table
pd.merge(left=cust,right=payment,on='customerid',how='')

   customerid firstname  lastname  address  amount         mode paymentdate
0           1      Mary     Smith    Delhi    60.0         Cash  2020-09-24
1           3     Linda  Williams    Udupi     NaN          NaN         NaN
2           4   Barbara     Jones  Chennai     NaN          NaN         NaN
3           2     Madan     Mohan   Mumbai   500.0  Credit Card  2020-04-27
4          17         R    Madhav      Goa   250.0  Credit Card  2021-04-01